site_name: My Docs

theme:
  name: material
  language: ru
  features:
    - tabs
      - navigation.tabs
      - content.code.annotate
      - navigation.tabs.sticky
      - navigation.instant
      - navigation.tracking
      - navigation.top
      - search.suggest
      - search.highlight

plugins:
  - i18n:
      default_language: ru
      docs_structure: suffix
      languages:
        ru:
          name: Russian
          build: true
        en:
          name: English
          build: true
      nav_translations:
        en:
          About Kaspresso: About Kaspresso
          About Kaspresso 2: About Kaspresso 2
        ru:
          About Kaspresso: О Kaspresso
          About Kaspresso 2: О Kaspresso 2

extra:
  material_alternate: true

nav:
  - About Kaspresso: index.md
  - About Kaspresso 2: 2.index.md

